package com.demo.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccount<M extends BaseAccount<M>> extends Model<M> implements IBean {

	public void setAccountId(java.lang.Integer accountId) {
		set("account_id", accountId);
	}

	public java.lang.Integer getAccountId() {
		return get("account_id");
	}

	public void setCash(java.lang.Long cash) {
		set("cash", cash);
	}

	public java.lang.Long getCash() {
		return get("cash");
	}

}
