package com.demo.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStaff<M extends BaseStaff<M>> extends Model<M> implements IBean {

	public void setStaffId(java.lang.Integer staffId) {
		set("staff_id", staffId);
	}

	public java.lang.Integer getStaffId() {
		return get("staff_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

}
