package com.demo.model;

import com.demo.base.BaseStaff;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Staff extends BaseStaff<Staff> {
	public static final Staff dao = new Staff();
}
