package com.demo.model;

import com.demo.base.BaseUserRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRecord extends BaseUserRecord<UserRecord> {
	public static final UserRecord dao = new UserRecord();
}
